# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tttest202211262',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tttest202211262',
                'lib_path': 'tttest202211262'},
  'syms': {'tttest202211262.core': {'tttest202211262.core.foo': ('core.html#foo', 'tttest202211262/core.py')}}}
